# Generated by Django 4.1.5 on 2023-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.TextField(),
        ),
    ]
