# Generated by Django 4.1.5 on 2023-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airline_airline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(max_length=30),
        ),
    ]
