# Generated by Django 4.1.5 on 2023-02-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_airline_airline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='name_airline', to='flights.airline'),
            preserve_default=False,
        ),
    ]
